#!/usr/bin/env node

const path = require('path');
const fs = require('fs');
const { scanRepo } = require('./scanner');
const { scoreRepo } = require('./scorer');
const { generateConfigs, generateBadgeMarkdown } = require('./generator');

async function run() {
  const isAction = !!process.env.GITHUB_ACTIONS;
  let repoPath, mode, outputDir, addBadge;

  if (isAction) {
    const core = require('@actions/core');
    try {
      repoPath = process.env.GITHUB_WORKSPACE || '.';
      mode = core.getInput('mode') || 'full';
      outputDir = core.getInput('output-dir') || '.';
      addBadge = core.getInput('badge') !== 'false';
      const createPr = core.getInput('create-pr') === 'true';

      const result = execute(repoPath, mode, outputDir, addBadge);

      core.setOutput('score', result.score);
      core.setOutput('grade', result.grade);
      core.setOutput('report', JSON.stringify(result));
      core.setOutput('files-generated', result.filesGenerated.join(','));

      // Create PR with generated configs if requested
      if (createPr && result.filesGenerated.length > 0) {
        await createConfigPr(core, result);
      }

      // Post summary to GitHub Actions
      core.summary
        .addHeading('AI Readiness Report', 2)
        .addRaw(`**Score: ${result.score}/100 (Grade: ${result.grade})**\n\n`)
        .addTable([
          [{ data: 'Category', header: true }, { data: 'Score', header: true }, { data: 'Max', header: true }, { data: 'Details', header: true }],
          ...result.breakdown.map(b => [b.category, String(b.score), String(b.max), b.reason])
        ])
        .addRaw('\n\n')
        .addRaw(`**Languages:** ${result.languages.map(l => l.language).join(', ')}\n`)
        .addRaw(`**Frameworks:** ${result.frameworks.join(', ') || 'None detected'}\n`);

      if (result.filesGenerated.length) {
        core.summary.addRaw(`\n**Generated:** ${result.filesGenerated.join(', ')}\n`);
      }

      if (result.prUrl) {
        core.summary.addRaw(`\n**PR Created:** ${result.prUrl}\n`);
        core.setOutput('pr-url', result.prUrl);
      }

      core.summary.write();

      if (result.score < 40) {
        core.warning(`AI Readiness score is ${result.score}/100 (Grade: ${result.grade}). Your repo could benefit from AI config files.`);
      }
    } catch (error) {
      core.setFailed(error.message);
    }
  } else {
    // CLI mode
    repoPath = process.argv[2] || '.';
    mode = process.argv[3] || 'full';
    outputDir = process.argv[4] || repoPath;
    addBadge = !process.argv.includes('--no-badge');

    const result = execute(repoPath, mode, outputDir, addBadge);
    printReport(result);
  }
}

async function createConfigPr(core, result) {
  const { execSync } = require('child_process');
  const github = require('@actions/github');

  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    core.warning('create-pr requires GITHUB_TOKEN. Set permissions: contents: write, pull-requests: write');
    return;
  }

  const octokit = github.getOctokit(token);
  const { owner, repo } = github.context.repo;
  const branchName = `ai-ready/add-configs-${Date.now()}`;
  const baseBranch = process.env.GITHUB_REF_NAME || 'main';

  try {
    // Configure git
    execSync('git config user.name "ai-ready[bot]"');
    execSync('git config user.email "ai-ready[bot]@users.noreply.github.com"');

    // Create branch and commit
    execSync(`git checkout -b ${branchName}`);
    for (const file of result.filesGenerated) {
      execSync(`git add "${file}"`);
    }
    execSync(`git commit -m "chore: add AI config files (score: ${result.score}/100)\n\nGenerated by ai-ready:\n${result.filesGenerated.map(f => '- ' + f).join('\n')}"`);
    execSync(`git push origin ${branchName}`);

    // Create PR
    const prBody = [
      `## AI Readiness: ${result.score}/100 (Grade: ${result.grade})`,
      '',
      'This PR adds AI coding tool configuration files generated by [ai-ready](https://github.com/M3phist0s/ai-ready).',
      '',
      '### Generated Files',
      ...result.filesGenerated.map(f => `- \`${f}\``),
      '',
      '### Score Breakdown',
      '| Category | Score | Max | Details |',
      '|----------|-------|-----|---------|',
      ...result.breakdown.map(b => `| ${b.category} | ${b.score} | ${b.max} | ${b.reason} |`),
      '',
      '### What these files do',
      '- **CLAUDE.md** — Instructions for Claude Code (project context, commands, conventions)',
      '- **.cursorrules** — Rules for Cursor AI (language + framework-specific guidance)',
      '- **.windsurfrules** — Rules for Windsurf AI (same format as .cursorrules)',
      '- **.github/copilot-instructions.md** — Instructions for GitHub Copilot',
      '',
      '---',
      '*Generated by [ai-ready](https://github.com/M3phist0s/ai-ready) — AI Readiness scorer and config generator*',
    ].join('\n');

    const { data: pr } = await octokit.rest.pulls.create({
      owner,
      repo,
      title: `Add AI config files (ai-ready score: ${result.score}/100)`,
      body: prBody,
      head: branchName,
      base: baseBranch,
    });

    result.prUrl = pr.html_url;
    core.info(`PR created: ${pr.html_url}`);
  } catch (error) {
    core.warning(`Failed to create PR: ${error.message}`);
  }
}

function execute(repoPath, mode, outputDir, addBadge) {
  repoPath = path.resolve(repoPath);
  outputDir = path.resolve(outputDir);

  // Scan
  const scan = scanRepo(repoPath);

  // Score
  const scoreResult = scoreRepo(scan);

  let filesGenerated = [];

  // Generate configs if mode is 'generate' or 'full'
  if (mode === 'generate' || mode === 'full') {
    filesGenerated = generateConfigs(scan, scoreResult, outputDir);
  }

  return {
    score: scoreResult.score,
    grade: scoreResult.grade,
    breakdown: scoreResult.breakdown,
    summary: scoreResult.summary,
    languages: scan.languages,
    frameworks: scan.frameworks,
    primaryLanguage: scan.primaryLanguage,
    existingAiConfigs: scan.existingAiConfigs,
    filesGenerated,
    badge: generateBadgeMarkdown(scoreResult.score),
    totalFiles: scan.totalFiles,
  };
}

function printReport(result) {
  console.log('');
  console.log('╔══════════════════════════════════════════════════════════╗');
  console.log('║                    AI READINESS REPORT                  ║');
  console.log('╚══════════════════════════════════════════════════════════╝');
  console.log('');
  console.log(`  Score: ${result.score}/100  Grade: ${result.grade}`);
  console.log(`  Files scanned: ${result.totalFiles}`);
  console.log(`  Primary language: ${result.primaryLanguage}`);
  if (result.frameworks.length) {
    console.log(`  Frameworks: ${result.frameworks.join(', ')}`);
  }
  console.log('');
  console.log('  ─── Breakdown ───');
  console.log('');

  for (const b of result.breakdown) {
    const bar = '█'.repeat(b.score) + '░'.repeat(b.max - b.score);
    const pad = b.category.padEnd(14);
    console.log(`  ${pad} ${bar} ${b.score}/${b.max}`);
    console.log(`  ${''.padEnd(14)} ${b.reason}`);
  }

  console.log('');

  if (result.existingAiConfigs.length) {
    console.log(`  Existing AI configs: ${result.existingAiConfigs.join(', ')}`);
  }

  if (result.filesGenerated.length) {
    console.log(`  Generated: ${result.filesGenerated.join(', ')}`);
  }

  console.log('');
  console.log('  ─── Badge ───');
  console.log('');
  console.log(`  ${result.badge}`);
  console.log('');
}

// Export for use by outreach.js and other scripts
module.exports = { execute };

// Run if called directly
if (require.main === module) {
  run();
}
