#!/usr/bin/env node

/**
 * ai-ready outreach engine
 * Finds repos without AI configs, forks them, generates configs, opens PRs.
 * Uses `gh` CLI for GitHub operations.
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const os = require('os');
const { execute } = require('./index');

const MAX_PRS = parseInt(process.env.MAX_PRS || '3');
const MIN_STARS = parseInt(process.env.MIN_STARS || '50');
const MAX_STARS = parseInt(process.env.MAX_STARS || '500');
const TARGET_LANGUAGES = (process.env.TARGET_LANGUAGES || 'javascript,typescript,python').split(',');
const OWNER = process.env.GITHUB_OWNER || 'M3phist0s';
const DRY_RUN = process.env.DRY_RUN === 'true';

// AI config files to check for
const AI_CONFIGS = ['CLAUDE.md', '.cursorrules', '.windsurfrules', '.github/copilot-instructions.md'];

function gh(args, opts = {}) {
  try {
    return execSync(`gh ${args}`, { encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'], ...opts }).trim();
  } catch (e) {
    if (opts.allowFail) return null;
    throw e;
  }
}

function ghApi(endpoint, opts = {}) {
  const raw = gh(`api "${endpoint}" --cache 1h`, { allowFail: opts.allowFail });
  if (raw === null) return null;
  try {
    return JSON.parse(raw);
  } catch {
    return raw;
  }
}

function log(msg) {
  const ts = new Date().toISOString().slice(0, 19);
  console.log(`[${ts}] ${msg}`);
}

function hasExistingPr(repoFullName) {
  // Check if we already opened a PR (open or closed) on this repo
  const result = gh(
    `pr list --repo "${repoFullName}" --author "${OWNER}" --state all --json number --limit 1`,
    { allowFail: true }
  );
  if (!result) return false;
  try {
    const prs = JSON.parse(result);
    return prs.length > 0;
  } catch {
    return false;
  }
}

function repoHasAiConfigs(repoFullName) {
  for (const config of AI_CONFIGS) {
    const result = ghApi(`repos/${repoFullName}/contents/${encodeURIComponent(config)}`, { allowFail: true });
    if (result && !result.message) return true;
  }
  return false;
}

function forkRepo(repoFullName) {
  log(`  Forking ${repoFullName}...`);
  gh(`repo fork "${repoFullName}" --clone=false`, { allowFail: true });
  // Wait briefly for fork to propagate
  execSync('sleep 3');
}

function createPrBody(repo, result, filesGenerated) {
  const lines = [
    `## Your repo's AI Readiness: ${result.score}/100 (Grade: ${result.grade})`,
    '',
    `Hi! I noticed **${repo.full_name}** doesn't have configuration files for AI coding tools yet.`,
    `This PR adds auto-generated configs so tools like [Claude Code](https://claude.ai/code), [Cursor](https://cursor.com), [Windsurf](https://codeium.com/windsurf), and [GitHub Copilot](https://github.com/features/copilot) can work more effectively with your codebase.`,
    '',
    '### What\'s included',
    '',
    ...filesGenerated.map(f => {
      const descriptions = {
        'CLAUDE.md': 'Project context and conventions for Claude Code',
        '.cursorrules': 'Language and framework-specific rules for Cursor AI',
        '.windsurfrules': 'AI coding rules for Windsurf (Codeium)',
        '.github/copilot-instructions.md': 'Custom instructions for GitHub Copilot',
      };
      return `- **\`${f}\`** — ${descriptions[f] || 'AI tool configuration'}`;
    }),
    '',
    '### Score breakdown',
    '',
    '| Category | Score | Max | Notes |',
    '|----------|-------|-----|-------|',
    ...result.breakdown.map(b => `| ${b.category} | ${b.score} | ${b.max} | ${b.reason} |`),
    '',
    '### Why this matters',
    '',
    'AI coding assistants work significantly better when they understand your project\'s structure, conventions, and tech stack. These config files provide that context — think of them as a README specifically for AI tools.',
    '',
    '---',
    '',
    'Generated by [ai-ready](https://github.com/lunacompsia-oss/ai-ready) — open-source AI readiness scorer and config generator.',
    'Feel free to edit the generated files to better match your project\'s specific conventions.',
  ];
  return lines.join('\n');
}

async function main() {
  log('=== ai-ready outreach engine ===');
  log(`Config: max=${MAX_PRS} PRs, stars=${MIN_STARS}-${MAX_STARS}, langs=${TARGET_LANGUAGES.join(',')}`);
  if (DRY_RUN) log('DRY RUN — no PRs will be created');
  log('');

  let prsCreated = 0;
  const results = [];

  for (const lang of TARGET_LANGUAGES) {
    if (prsCreated >= MAX_PRS) break;

    // Search for repos in this language
    const sixMonthsAgo = new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10);
    const query = `language:${lang} stars:${MIN_STARS}..${MAX_STARS} pushed:>${sixMonthsAgo} fork:false archived:false`;
    log(`Searching: ${query}`);

    const searchResult = ghApi(
      `search/repositories?q=${encodeURIComponent(query)}&sort=updated&per_page=30`
    );

    if (!searchResult || !searchResult.items) {
      log(`  No results for ${lang}`);
      continue;
    }

    log(`  Found ${searchResult.items.length} candidates`);

    for (const repo of searchResult.items) {
      if (prsCreated >= MAX_PRS) break;

      const name = repo.full_name;
      log(`\nEvaluating: ${name} (${repo.stargazers_count} stars)`);

      // Skip if we already targeted this repo
      if (hasExistingPr(name)) {
        log(`  SKIP: already have PR on ${name}`);
        continue;
      }

      // Skip if repo already has AI configs
      if (repoHasAiConfigs(name)) {
        log(`  SKIP: ${name} already has AI configs`);
        continue;
      }

      // Skip profile README repos (repo name == owner name)
      const [ownerName, repoName] = name.split('/');
      if (repoName.toLowerCase() === ownerName.toLowerCase()) {
        log(`  SKIP: ${name} is a profile README repo`);
        continue;
      }

      // Skip if repo is too small (likely not a real project)
      if (repo.size < 50) {
        log(`  SKIP: ${name} too small (${repo.size} KB)`);
        continue;
      }

      // Skip repos with no description (low quality signal)
      if (!repo.description) {
        log(`  SKIP: ${name} has no description`);
        continue;
      }

      log(`  TARGET: ${name} — no AI configs, ${repo.stargazers_count} stars`);

      if (DRY_RUN) {
        results.push({ repo: name, status: 'dry-run' });
        prsCreated++;
        continue;
      }

      // Fork and clone
      const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'ai-ready-outreach-'));
      try {
        forkRepo(name);

        // Clone the fork
        const repoName = name.split('/')[1];
        const cloneDir = path.join(tmpDir, repoName);
        log(`  Cloning fork to ${cloneDir}...`);
        execSync(`git clone --depth 1 "https://github.com/${OWNER}/${repoName}.git" "${cloneDir}"`, {
          stdio: 'pipe',
        });

        // Run ai-ready in generate mode
        log(`  Running ai-ready...`);
        const result = execute(cloneDir, 'full', cloneDir, false);
        log(`  Score: ${result.score}/100 (${result.grade}), generated: ${result.filesGenerated.length} files`);

        if (result.filesGenerated.length === 0) {
          log(`  SKIP: no files to generate for ${name}`);
          results.push({ repo: name, status: 'no-files-generated', score: result.score });
          continue;
        }

        // Create branch, commit, push
        const branchName = 'ai-ready/add-configs';
        execSync(`git -C "${cloneDir}" checkout -b "${branchName}"`, { stdio: 'pipe' });
        execSync(`git -C "${cloneDir}" config user.name "ai-ready[bot]"`, { stdio: 'pipe' });
        execSync(`git -C "${cloneDir}" config user.email "ai-ready[bot]@users.noreply.github.com"`, { stdio: 'pipe' });

        for (const f of result.filesGenerated) {
          execSync(`git -C "${cloneDir}" add "${f}"`, { stdio: 'pipe' });
        }

        const commitMsg = `chore: add AI coding tool configurations

Generated by ai-ready (score: ${result.score}/100)

Files added:
${result.filesGenerated.map(f => '- ' + f).join('\n')}

These config files help AI coding tools (Claude Code, Cursor, Windsurf,
GitHub Copilot) understand your project's structure and conventions.

Learn more: https://github.com/lunacompsia-oss/ai-ready`;

        execSync(`git -C "${cloneDir}" commit -m "${commitMsg.replace(/"/g, '\\"')}"`, { stdio: 'pipe' });
        execSync(`git -C "${cloneDir}" push origin "${branchName}"`, { stdio: 'pipe' });

        // Open PR to original repo
        const prBody = createPrBody(repo, result, result.filesGenerated);
        const prBodyFile = path.join(tmpDir, 'pr-body.md');
        fs.writeFileSync(prBodyFile, prBody);

        const prUrl = gh(
          `pr create --repo "${name}" --head "${OWNER}:${branchName}" --title "Add AI coding tool configurations" --body-file "${prBodyFile}"`
        );

        log(`  PR CREATED: ${prUrl}`);
        results.push({ repo: name, status: 'pr-created', pr: prUrl, score: result.score });
        prsCreated++;

      } catch (err) {
        log(`  ERROR on ${name}: ${err.message}`);
        results.push({ repo: name, status: 'error', error: err.message });
      } finally {
        // Cleanup
        try {
          fs.rmSync(tmpDir, { recursive: true, force: true });
        } catch {}
      }
    }
  }

  // Summary
  log('\n=== OUTREACH SUMMARY ===');
  log(`PRs created: ${prsCreated}/${MAX_PRS}`);
  for (const r of results) {
    log(`  ${r.repo}: ${r.status}${r.pr ? ' — ' + r.pr : ''}${r.score ? ' (score: ' + r.score + ')' : ''}`);
  }

  // Write results to file for GitHub Actions summary
  const summaryFile = process.env.GITHUB_STEP_SUMMARY;
  if (summaryFile) {
    const summary = [
      '## AI Ready Outreach Results',
      '',
      `**PRs created:** ${prsCreated}`,
      '',
      '| Repo | Status | Score | PR |',
      '|------|--------|-------|----|',
      ...results.map(r =>
        `| ${r.repo} | ${r.status} | ${r.score || '-'} | ${r.pr ? `[Link](${r.pr})` : '-'} |`
      ),
    ].join('\n');
    fs.appendFileSync(summaryFile, summary);
  }

  return results;
}

main().catch(err => {
  console.error('Fatal error:', err);
  process.exit(1);
});
